import requests
from bs4 import BeautifulSoup
import csv

urls = [
  'http://catalogue.uottawa.ca/en/courses/cpt/',
  'http://catalogue.uottawa.ca/en/courses/adm/',
  'http://catalogue.uottawa.ca/en/courses/amm/',
  'http://catalogue.uottawa.ca/en/courses/afr/',
  'http://catalogue.uottawa.ca/en/courses/ana/',
  'http://catalogue.uottawa.ca/en/courses/anp/',
  'http://catalogue.uottawa.ca/en/courses/ane/',
  'http://catalogue.uottawa.ca/en/courses/ant/',
  'http://catalogue.uottawa.ca/en/courses/arb/',
  'http://catalogue.uottawa.ca/en/courses/cla/',
  'http://catalogue.uottawa.ca/en/courses/lcl/',
  'http://catalogue.uottawa.ca/en/courses/cli/',
  'http://catalogue.uottawa.ca/en/courses/cml/',
  'http://catalogue.uottawa.ca/en/courses/cmn/',
  'http://catalogue.uottawa.ca/en/courses/cpl/',
  'http://catalogue.uottawa.ca/en/courses/ceg/',
  'http://catalogue.uottawa.ca/en/courses/csi/',
  'http://catalogue.uottawa.ca/en/courses/ech/',
  'http://catalogue.uottawa.ca/en/courses/crm/',
  'http://catalogue.uottawa.ca/en/courses/sec/',
  'http://catalogue.uottawa.ca/en/courses/arb/',
  'http://catalogue.uottawa.ca/en/courses/acp/',
  'http://catalogue.uottawa.ca/en/courses/amt/',
  'http://catalogue.uottawa.ca/en/courses/asi/',
  'http://catalogue.uottawa.ca/en/courses/bil/',
  'http://catalogue.uottawa.ca/en/courses/bch/',
  'http://catalogue.uottawa.ca/en/courses/bnf/',
  'http://catalogue.uottawa.ca/en/courses/bio/',
  'http://catalogue.uottawa.ca/en/courses/bmg/',
  'http://catalogue.uottawa.ca/en/courses/bim/',
  'http://catalogue.uottawa.ca/en/courses/bps/',
  'http://catalogue.uottawa.ca/en/courses/cdn/',
  'http://catalogue.uottawa.ca/en/courses/cts/',
  'http://catalogue.uottawa.ca/en/courses/cmm/',
  'http://catalogue.uottawa.ca/en/courses/clt/',
  'http://catalogue.uottawa.ca/en/courses/tox/',
  'http://catalogue.uottawa.ca/en/courses/chg/',
  'http://catalogue.uottawa.ca/en/courses/chm/',
  'http://catalogue.uottawa.ca/en/courses/chn/',
  'http://catalogue.uottawa.ca/en/courses/cvg/',
  'http://catalogue.uottawa.ca/en/courses/drc/',
  'http://catalogue.uottawa.ca/en/courses/sds/',
  'http://catalogue.uottawa.ca/en/courses/dcn/',
  'http://catalogue.uottawa.ca/en/courses/dhn/',
  'http://catalogue.uottawa.ca/en/courses/dti/',
  'http://catalogue.uottawa.ca/en/courses/thd/',
  'http://catalogue.uottawa.ca/en/courses/eco/',
  'http://catalogue.uottawa.ca/en/courses/edu/',
  'http://catalogue.uottawa.ca/en/courses/ped/',
  'http://catalogue.uottawa.ca/en/courses/ele/',
  'http://catalogue.uottawa.ca/en/courses/elg/',
  'http://catalogue.uottawa.ca/en/courses/cgi/',
  'http://catalogue.uottawa.ca/en/courses/sed/',
  'http://catalogue.uottawa.ca/en/courses/emp/',
  'http://catalogue.uottawa.ca/en/courses/eng/',
  'http://catalogue.uottawa.ca/en/courses/esl/',
  'http://catalogue.uottawa.ca/en/courses/eed/',
  'http://catalogue.uottawa.ca/en/courses/evg/',
  'http://catalogue.uottawa.ca/en/courses/evs/',
  'http://catalogue.uottawa.ca/en/courses/env/',
  'http://catalogue.uottawa.ca/en/courses/evd/',
  'http://catalogue.uottawa.ca/en/courses/epi/',
  'http://catalogue.uottawa.ca/en/courses/fam/',
  'http://catalogue.uottawa.ca/en/courses/fem/',
  'http://catalogue.uottawa.ca/en/courses/cin/',
  'http://catalogue.uottawa.ca/en/courses/nut/',
  'http://catalogue.uottawa.ca/en/courses/efr/',
  'http://catalogue.uottawa.ca/en/courses/fls/',
  'http://catalogue.uottawa.ca/en/courses/iai/',
  'http://catalogue.uottawa.ca/en/courses/ahl/',
  'http://catalogue.uottawa.ca/en/courses/dvm/',
  'http://catalogue.uottawa.ca/en/courses/sai/',
  'http://catalogue.uottawa.ca/en/courses/ita/',
  'http://catalogue.uottawa.ca/en/courses/jpn/',
  'http://catalogue.uottawa.ca/en/courses/jou/',
  'http://catalogue.uottawa.ca/en/courses/fre/',
  'http://catalogue.uottawa.ca/en/courses/gae/',
  'http://catalogue.uottawa.ca/en/courses/gng/',
  'http://catalogue.uottawa.ca/en/courses/gsu/',
  'http://catalogue.uottawa.ca/en/courses/geg/',
  'http://catalogue.uottawa.ca/en/courses/geo/',
  'http://catalogue.uottawa.ca/en/courses/alg/',
  'http://catalogue.uottawa.ca/en/courses/ela/',
  'http://catalogue.uottawa.ca/en/courses/dcc/',
  'http://catalogue.uottawa.ca/en/courses/dcl/',
  'http://catalogue.uottawa.ca/en/courses/lsr/',
  'http://catalogue.uottawa.ca/en/courses/fra/',
  'http://catalogue.uottawa.ca/en/courses/lin/',
  'http://catalogue.uottawa.ca/en/courses/alg/',
  'http://catalogue.uottawa.ca/en/courses/grt/',
  'http://catalogue.uottawa.ca/en/courses/mgt/',
  'http://catalogue.uottawa.ca/en/courses/thm/',
  'http://catalogue.uottawa.ca/en/courses/mat/',
  'http://catalogue.uottawa.ca/en/courses/mba/',
  'http://catalogue.uottawa.ca/en/courses/mcg/',
  'http://catalogue.uottawa.ca/en/courses/inr/',
  'http://catalogue.uottawa.ca/en/courses/med/',
  'http://catalogue.uottawa.ca/en/courses/pcs/',
  'http://catalogue.uottawa.ca/en/courses/mdv/',
  'http://catalogue.uottawa.ca/en/courses/mic/',
  'http://catalogue.uottawa.ca/en/courses/llm/',
  'http://catalogue.uottawa.ca/en/courses/mus/',
  'http://catalogue.uottawa.ca/en/courses/ila/',
  'http://catalogue.uottawa.ca/en/courses/hah/',
  'http://catalogue.uottawa.ca/en/courses/mha/',
  'http://catalogue.uottawa.ca/en/courses/hss/',
  'http://catalogue.uottawa.ca/en/courses/mhs/',
  'http://catalogue.uottawa.ca/en/courses/his/',
  'http://catalogue.uottawa.ca/en/courses/hmg/',
  'http://catalogue.uottawa.ca/en/courses/apa/',
  'http://catalogue.uottawa.ca/en/courses/imm/',
  'http://catalogue.uottawa.ca/en/courses/ila/',
  'http://catalogue.uottawa.ca/en/courses/isi/',
  'http://catalogue.uottawa.ca/en/courses/obg/',
  'http://catalogue.uottawa.ca/en/courses/iti/',
  'http://catalogue.uottawa.ca/en/courses/nap/',
  'http://catalogue.uottawa.ca/en/courses/nsc/',
  'http://catalogue.uottawa.ca/en/courses/not/',
  'http://catalogue.uottawa.ca/en/courses/nsg/',
   "http://catalogue.uottawa.ca/en/courses/obg/",
   "http://catalogue.uottawa.ca/en/courses/erg/",
    "http://catalogue.uottawa.ca/en/courses/omt/",
    "http://catalogue.uottawa.ca/en/courses/oph/",
    "http://catalogue.uottawa.ca/en/courses/ort/",
    "http://catalogue.uottawa.ca/en/courses/pme/",
    "http://catalogue.uottawa.ca/en/courses/scs/",
    "http://catalogue.uottawa.ca/en/courses/sss/",
    "http://catalogue.uottawa.ca/en/courses/svs/",
    "http://catalogue.uottawa.ca/en/courses/soc/",
    "http://catalogue.uottawa.ca/en/courses/seg/",
    "http://catalogue.uottawa.ca/en/courses/esp/",
    "http://catalogue.uottawa.ca/en/courses/ora/",
    "http://catalogue.uottawa.ca/en/courses/sys/",
    "http://catalogue.uottawa.ca/en/courses/the/",
    "http://catalogue.uottawa.ca/en/courses/tra/",
    "http://catalogue.uottawa.ca/en/courses/tmm/",
    "http://catalogue.uottawa.ca/en/courses/pae/",
    "http://catalogue.uottawa.ca/en/courses/pha/",
    "http://catalogue.uottawa.ca/en/courses/phi/",
    "http://catalogue.uottawa.ca/en/courses/phy/",
    "http://catalogue.uottawa.ca/en/courses/phs/",
    "http://catalogue.uottawa.ca/en/courses/pht/",
    "http://catalogue.uottawa.ca/en/courses/pln/",
    "http://catalogue.uottawa.ca/en/courses/pol/",
    "http://catalogue.uottawa.ca/en/courses/pop/",
    "http://catalogue.uottawa.ca/en/courses/phr/",
    "http://catalogue.uottawa.ca/en/courses/por/",
    "http://catalogue.uottawa.ca/en/courses/pip/",
    "http://catalogue.uottawa.ca/en/courses/art/",
    "http://catalogue.uottawa.ca/en/courses/psy/",
    "http://catalogue.uottawa.ca/en/courses/pct/",
    "http://catalogue.uottawa.ca/en/courses/pap/",
    "http://catalogue.uottawa.ca/en/courses/api/",
    "http://catalogue.uottawa.ca/en/courses/pbh/",
    "http://catalogue.uottawa.ca/en/courses/rad/",
    "http://catalogue.uottawa.ca/en/courses/rea/",
    "http://catalogue.uottawa.ca/en/courses/srs/",
    "http://catalogue.uottawa.ca/en/courses/rch/",
    "http://catalogue.uottawa.ca/en/courses/rus/",
    "http://catalogue.uottawa.ca/en/courses/sci/",
    "http://catalogue.uottawa.ca/en/courses/isp/",
    "http://catalogue.uottawa.ca/en/courses/dls/",
    "http://catalogue.uottawa.ca/en/courses/fss/",
    "http://catalogue.uottawa.ca/en/courses/lcm/",
    "http://catalogue.uottawa.ca/en/courses/ydd/",
    "http://catalogue.uottawa.ca/en/courses/glo/",
    "http://catalogue.uottawa.ca/en/courses/uro/",
    "http://catalogue.uottawa.ca/en/courses/jcs/"
]

# Create a list to store the extracted data
data = []
for url in urls:
    # Send a GET request to the webpage
    response = requests.get(url)

    # Parse the HTML content
    soup = BeautifulSoup(response.content, "html.parser")

    # Find all the course elements on the page
    course_elements = soup.find_all("div", class_="courseblock")

    # Extract the course code and description from each course element
    for course_element in course_elements:
        course_code_element = course_element.find("p", class_="courseblocktitle noindent")
        course_description_element = course_element.find("p", class_="courseblockdesc noindent")
        
        # Check if the elements exist before accessing their text attribute
        if course_code_element is not None and course_description_element is not None:
            course_code = course_code_element.text.strip()
            course_description = course_description_element.text.strip()
            data.append([course_code, course_description])

# Save the data as a CSV file
filename = "course_data.csv"
with open(filename, "w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["Course Code", "Course Description"])
    writer.writerows(data)

print("CSV file saved successfully!")
