# Generated by Django 4.2.2 on 2023-07-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Results_course',
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_course_code', models.CharField(max_length=10)),
                ('searched_course_number', models.CharField(max_length=10)),
                ('searched_course_name', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('prof_name', models.CharField(max_length=100)),
                ('textbook_required', models.BooleanField()),
                ('prereq', models.BooleanField()),
                ('delivery', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.course')),
            ],
            options={
                'db_table': 'Rating_course',
            },
        ),
    ]
