# Generated by Django 4.2.2 on 2023-07-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_alter_course_table_usercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='searched_course_name',
            new_name='course_name',
        ),
    ]
